#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# Set a default POSTGRES_USER if it is not set
if [ -z "${POSTGRES_USER}" ]; then
    base_postgres_image_default_user='postgres'
    export POSTGRES_USER="${base_postgres_image_default_user}"
fi

export DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"

# Wait for PostgreSQL to be ready
until pg_isready -h "${POSTGRES_HOST}" -p "${POSTGRES_PORT}" -U "${POSTGRES_USER}"; do
    >&2 echo "Waiting for PostgreSQL to become available..."
    sleep 1
done

>&2 echo 'PostgreSQL is available'

exec "$@"